### ISSUE TITLE
Do you mean `XXXX` Generator?

### ISSUE THREAD

**Issue by cpreston321** [unjs/automd#20]
### Describe the feature

If they misstyped `pm-isntall` we warn them and say do you mean `pm-install` ? Kinda silly but it's nice to have small things like this since there isn't no intelisense.  

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
That would be a nice idea! We might use fuzzy search for available generators. There are couple of "did you mean" npm packages I let you make some research if found a lightweight and modern one. (otherwise we can also use fuse.js or make an inline fork of of of them)

**Comment by cpreston321** [comment]
I found https://www.npmjs.com/package/didyoumean2 which seems promising.
