### ISSUE TITLE
Badge Generator

### ISSUE THREAD

**Issue by pi0** [unjs/automd#3]

**Comment by cpreston321** [comment]
@pi0 whats the expectation with this. I was going to implement this after #9. Like default badges img shield and best way to enable / disable certain badges.

**Comment by uncenter** [comment]
I had this on my todo list as well, something like this imo:

```md
<!-- AUTOMD_START generator="badge" npm-version="true" npm-downloads="true" -->
```

...or

```md
<!-- AUTOMD_START generator="badge" badges="npm-version npm-downloads" -->
```
