### ISSUE TITLE
automd rewrites md files on demand and errors out and crashes dev mode.

### ISSUE THREAD

**Issue by cpreston321** [unjs/automd#35]
### Environment

any

### Reproduction

https://github.com/unjs/automd

### Describe the bug

`bun i && bun dev` modify md files and you'll see specially `pm-i` keeps duplicating itself.

### Additional context

![CleanShot 2024-02-23 at 16 15 29@2x](https://github.com/unjs/automd/assets/6619884/c9d1c43e-0297-4949-8d10-f167e9f6ab7c)

![CleanShot 2024-02-23 at 16 17 10@2x](https://github.com/unjs/automd/assets/6619884/21b619e6-9895-40c7-b629-1478369b4a53)

![CleanShot 2024-02-23 at 16 17 23@2x](https://github.com/unjs/automd/assets/6619884/b7d56873-4c98-4072-ab91-f08eb9c91a6d)

**Comment by pi0** [comment]
Related: https://github.com/unjs/automd/commit/977c2c3450db5df6dd9c8469c022e1de1430a26e

**Comment by cpreston321** [comment]
This did wasn't working for JSDocs either.

**Comment by pi0** [comment]
Yeah i think that one is more serious I had it too but definitely not automd :D
