### ISSUE TITLE
package manager command generators

### ISSUE THREAD

**Issue by pi0** [unjs/automd#5]
- [x] `pm-install` (#9)
- [ ] `pm-x`

**Comment by uncenter** [comment]
Would support for `npx`/`bunx`/`pnpm dlx` be a separate generator or an option in the `pm-install` generator? It could be a different generator, say `pm-run`?

**Comment by pi0** [comment]
Surely feel free to directly open a PR after #9 👍🏼 (I am thinking we might use shorter `pm-x` also for undocs wdyt?

**Comment by cpreston321** [comment]
> wdyt?

I like that! pm-x
