### ISSUE TITLE
Add the ability to disable some package manager for the installation

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/automd#76]
### Describe the feature

Hello,

The `pm-i` generator generates content for a lot of different package managers like `pnpm`, `bun`, and `deno` but I would like to have the ability to remove some of them

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Picking some favorite options is against unjs (and this project's) goals of being agnostic.

We can alternatively support an option to make `pm-i toggle` to make readme shorter. would that be something working for you?

**Comment by pi0** [comment]
issue/pr is welcome for toggle.
